spring.application.name=bidpulse
spring.datasource.url=jdbc:mysql://localhost:3306/bidpulse_db
spring.datasource.username=root
spring.datasource.password=Riyaz@2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jackson.deserialization.fail-on-unknown-properties=false

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
